resources:
  - name: bambooGit
    type: GitRepo
    configuration:
      path: yahavi/bamboo-artifactory-plugin
      gitProvider: yahav_github
      buildOn:
        pullRequestCreate: true

pipelines:
  - name: test_bamboo
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog-ecosystem-integration-env
            tag: 1.0.0
            options: -m=8g --memory-swap=-1
      environmentVariables:
        readOnly:
          CI: "true"
          ARTIFACTORY_URL: $int_jfrog_rt_url
          ARTIFACTORY_USERNAME: $int_jfrog_rt_user
          ARTIFACTORY_PASSWORD: $int_jfrog_rt_password

    steps:
      - name: Integration_Tests
        type: Bash
        configuration:
          inputResources:
            - name: bambooGit
          integrations:
            - name: jfrog
        execution:
          onStart:
            - update_commit_status bambooGit --context "$step_name"
          onExecute:
            - restore_cache_files m2_home ${HOME}/.m2
            - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
            - echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
            - source "/root/.sdkman/bin/sdkman-init.sh" && sdk update && sdk install java 8.0.275.hs-adpt
            - git clone https://github.com/jfrog/jfrog-testing-infra.git
            - cd jfrog-testing-infra
            - git checkout code-review
            - ./gradlew clean build publishToMavenLocal
            - cd $res_bambooGit_resourcePath
            - sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
            - curl -fL https://packages.atlassian.com/api/gpg/key/public -o public
            - apt-key add public
            - apt update && apt install libtcnative-1 atlassian-plugin-sdk -y
            - ln -sv /usr/lib/x86_64-linux-gnu/libtcnative-1.so /usr/lib/
            - atlas-version
            - atlas-integration-test -B -Djava.security.egd=file:/dev/./urandom --jvmargs "-Xms512M -Xmx1024M"
          onComplete:
            - save_tests $res_bambooGit_resourcePath/target/group-it/tomcat85x/surefire-reports/
            - add_run_files $res_bambooGit_resourcePath/target/bamboo/home/logs/atlassian-bamboo.log atlassian-bamboo.log
            - add_run_files $res_bambooGit_resourcePath/target/container/tomcat8x/cargo-bamboo-home/bamboo-agent-home/logs/atlassian-bamboo.log atlassian-bamboo-agent.log || true
            - update_commit_status bambooGit --context "$step_name"
            - add_cache_files ${HOME}/.m2 m2_home
